on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint

  test:
    name: test (node ${{ matrix.node }}, mongodb ${{ matrix.mongo }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
        mongo: [latest]
        include:
          - { node: 20, mongo: 7.0.25 }
          - { node: 20, mongo: 6.0.11 }
          - { node: 20, mongo: 5.0.22 }
          - { node: 20, mongo: 4.4.25 }
          - { node: 20, mongo: 3.6.23 }
          - { node: 20, mongo: 2.6.12 }
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Disable AppArmor User Namespace Restrictions, required to open
          Chrome on Ubuntu 23.10+ without --no-sandbox). See
          https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md.
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - run: npm ci
      - run: npm run test:unit

      - name: Supply MongoDB ${{ matrix.mongo }}
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongo }}
      - name: Supply integration test configuration file
        run: cp config/test.sample.json config/test.json
      - name: Make webservice available to be integration-tested
        run: NODE_ENV=test node index.js &
      - run: sleep 10s

      - run: npm run test:integration
